### ISSUE TITLE
Service address on multi-homed client

### ISSUE THREAD

**Issue by terezivy** [smoketurner/dropwizard-consul#109]
Is there are a way to specify the network adapter/ip subnet to use when a service is registered on a multi-homed client and the host name and or IP isn't known until runtime. When a client is dynamically created, on say AWS or a VM newly instantiated, with multiple network adapters, on different subnets, and the service is only listening on a single one of those adapters. For example, the client has adapters on 192.168.1.34/ 192.168.2.12/192.168.63, I would like to specify the subnet the service should register with. Since I won't know the host name nor the IP when the configuration is created, would it be reasonable to provide the consul factory with a subnet and allow it to choose any network address that falls within that subnet? Better yet, provide the consul factory with a supplier that could be evaluated when the lifecycle listener actually calls the register method and the information regarding the which adapters/IP the service is listening on are available? Or is there some better/already existing method for addressing this situation? Thanks!

**Comment by jplock** [comment]
Welcome to review a pull request if you want to play around with this.

**Comment by terezivy** [comment]
Cool, I will put something together. Thanks! Happy Quarantining!

**Comment by terezivy** [comment]
Just swinging back around. Is there anything else I need to add to this to get it merged? Have a great day, thanks!
