### ISSUE TITLE
Allow for property replacement from service registry as well as kv

### ISSUE THREAD

**Issue by delphyne** [smoketurner/dropwizard-consul#11]
I was going to start working on this in my own fork, but hoped to solicit feedback about the approach before doing so, since I'd like to contribute it back to you.  Right now, this library works very well for pulling prop replacements from Consul KV.  However, there are reasons that pulling from the service registry would be extremely useful as well.  For example, Cassandra seeds.

Anyway, my strawman right now is that the keyspace is currently relatively flat.  I was thinking of having the library expect a structured keyspace with a prefix that specifies from where in Consul you wish to search.  It would default to KV for backwards compatibility and convenience purposes, but could manually be namespaced into KV in the case of of collision.

for example:
`${foo/bar/baz}` looks up the value for `foo/bar/baz` in kv
`${service:foo/bar/baz}` looks up the service "foo/bar/baz" in catalog/services
`${kv:service:foo/bar/baz}` looks up `service:foo/bar/baz` in kv to allow for the possibility of `service:` as a prefix to a key name (unlikely, but flexible...)

Service lookups would return a JSON array of:

``` java
Optional
    .fromNullable(Strings.emptyToNull(service.ServiceAddress)
    .or(service.Address)
    .transform(s -> service.ServicePort == null ? s : String.format("%s:%s", s, service.ServicePort))
```

Any thoughts about this?

**Comment by jplock** [comment]
As long as backward compatibility is maintained and you could include some tests for this, this sounds great.
