### ISSUE TITLE
Possible Next Release 

### ISSUE THREAD

**Issue by terezivy** [smoketurner/dropwizard-consul#146]
Hello, I am wondering if there is a timeline for your next release. If that is somewhat far off, would it be possible to get a snapshot released in order that I can make use of a couple of the most recent commits making the healthcheck url configurable? Thanks, and much appreciated!

**Comment by jplock** [comment]
I recently switched computers and have been having difficulty getting GPG signing working again when pushing to Maven Central.  It's on my list of things to do, but not a high priority for me at the moment.
