### ISSUE TITLE
Version 1.0.3-2 not found

### ISSUE THREAD

**Issue by AMeng** [smoketurner/dropwizard-consul#20]
Maven still lists `1.0.3-1` as the latest version.

**Comment by jplock** [comment]
I pushed this yesterday.  I don't know what happened on why nothing was released

**Comment by AMeng** [comment]
Would you mind pushing it again? You can see the Maven repo doesn't list it still:
http://repo1.maven.org/maven2/com/smoketurner/dropwizard/dropwizard-consul/

**Comment by jplock** [comment]
I just tried to push this again

**Comment by jplock** [comment]
Looks like its available now, closing
