### ISSUE TITLE
loadbalancr example with ribbon

### ISSUE THREAD

**Issue by gadieichhorn** [smoketurner/dropwizard-consul#22]
Your example work perfectly!

Can you share example how you would use the LB option on the RibbonJersyClient?
Let say I have few other resource applications I want to call from the hello world app example.
Discovery is made through Consul.

a client app aggregating data from a Data service before return to caller.
UI -> aggregate -> Data

Thanks in advance

p.s. I am happy to fork an example skeleton and let you do the wiring.

**Comment by jplock** [comment]
If you are following the example application, you should be able to do something like:

```
final RibbonJerseyClientBuilder builder = new RibbonJerseyClientBuilder(environment, consul, configuration.getClient());
final RibbonJerseyClient client1 = builder.build('client1');
final RibbonJerseyClient client2 = builder.build('client2');
```

to set up multiple load balancing clients going to separate downstream services.
