### ISSUE TITLE
Add support for a simple server type with single connector

### ISSUE THREAD

**Issue by ihr** [smoketurner/dropwizard-consul#24]
Hi guys,

It would be good to have support for the following Dropwizard configuration:

    server:
      type: simple
      applicationContextPath: /application
      adminContextPath: /admin
      connector:
        type: http
        port: 8080

**Comment by jplock** [comment]
Good idea, I'll see if I can work on this.

**Comment by jplock** [comment]
@ihr actually, this should already work - https://github.com/smoketurner/dropwizard-consul/blob/master/consul-core/src/main/java/com/smoketurner/dropwizard/consul/core/ConsulAdvertiser.java#L192 what is not working for you?

**Comment by ihr** [comment]
Hi @jplock,

The problem is that the program flow goes to https://github.com/smoketurner/dropwizard-consul/blob/master/consul-core/src/main/java/com/smoketurner/dropwizard/consul/core/ConsulServiceListener.java#L64 
which results in triggering https://github.com/smoketurner/dropwizard-consul/blob/master/consul-core/src/main/java/com/smoketurner/dropwizard/consul/core/ConsulServiceListener.java#L70

**Comment by jplock** [comment]
ah ok, thanks for the explanation, I'll look into it

**Comment by jplock** [comment]
@ihr does #25 look like it will fix the issue?  Testing locally it seems to work fine.

**Comment by ihr** [comment]
@jplock this was my quick fix as well :) however, it's good to check that the port is within the range https://github.com/smoketurner/dropwizard-consul/blob/master/consul-core/src/main/java/com/smoketurner/dropwizard/consul/core/ConsulServiceListener.java#L56

**Comment by jplock** [comment]
I just pushed up 1.0.5-3 with this fix.
