### ISSUE TITLE
Support to specify a service-specific IP address

### ISSUE THREAD

**Issue by FraBle** [smoketurner/dropwizard-consul#3]
The registration of a service with Consul can include a service address ([docs](https://www.consul.io/docs/agent/http/agent.html#agent_service_register)).
In my use case I have different docker containers, one for Consul (server and agent), one for my Dropwizard service with your dropwizard-consul bundle.
I opened an issue for consul-client by OrbitzWorldwide [#106](https://github.com/OrbitzWorldwide/consul-client/issues/106) in which they describe how it is possible to pass the service address as a parameter by using a registration builder.
If dropwizard-consul would adapt this, it would remove the restriction, that the Consul agent and Dropwizard service are running on the same machine (e.g. in Docker scenarios).

**Comment by jplock** [comment]
I think I actually had this at one point, then decided to remove it.  I'll see what I can do.

**Comment by FraBle** [comment]
I currently work on a patch/feature for a pull request. I would submit it soon. Maybe you can have a look at it later.

**Comment by jplock** [comment]
If you can submit a PR I'll happily review it.  Thanks!

**Comment by FraBle** [comment]
The code is ready so for, I guess. But I'm having hard times to adjust the tests: I'm not sure how to mock the consul-client registration builder. Any attempt throws more errors so far.
