### ISSUE TITLE
ConsulFactory

### ISSUE THREAD

**Issue by ryansmithevans** [smoketurner/dropwizard-consul#31]
No equality/hashcode implemented

**Comment by jplock** [comment]
Does it need one?  The only time its reference is on startup when the configuration is parsed.

**Comment by ryansmithevans** [comment]
I was in the process of writing a test which verified my application had correctly created and serialised a 'ConsulFactory', and instead of doing a simple equals to my expected object, I had to extract each internal object used and test explicitly. 

Java objects should typically have hashcode/equals implemented, but this is especially important for POJO like objects.

I've provided a PR here:- https://github.com/smoketurner/dropwizard-consul/pull/33

**Comment by jplock** [comment]
I just pushed up v1.1.0-2 to Maven Central with these fixes.  Thanks!
