### ISSUE TITLE
working with default values failing

### ISSUE THREAD

**Issue by dorperetz** [smoketurner/dropwizard-consul#37]
hello,

when workin with no default values in the yml file ( conf : {consul/conf} ) everything is fine.
once adding default value to the yml ( conf : {consul/conf:-0}) it fails.
according to the log the problem is that it looks for an key named consul/conf:-0 instead of consul/conf,

are you familier with the problem ? how can i fix this ?

**Comment by jplock** [comment]
I haven't seen this.  Can you post your consul config as a comment in here so I can try and replicate?
