### ISSUE TITLE
Support for ACLs and X-Consul-Token

### ISSUE THREAD

**Issue by jadams74** [smoketurner/dropwizard-consul#42]
I'm not seeing support for passing a token to Consul. Can you point me to the code if its just missing in the documentation? I've been looking through the code and not seeing any option. Is a blocker for me to get Dockerized API into Nomad cluster.

In the mean time I'm going to start writing some code to this end and create a PR here.  Point me to any doco I need for standards, otherwise, I'll follow what I see. In the files. If you have already thought this out, point me the right direction and I'll run with it.

**Comment by jplock** [comment]
Sounds good.  Please just follow the existing code (spaces for indentation, don't use `*` imports, etc.)

**Comment by jadams74** [comment]
just saw the related readmes

**Comment by jadams74** [comment]
@jplock  I'm confused why this is in initialize. 

https://github.com/smoketurner/dropwizard-consul/blob/a96a70dd730af652405763c0a6b8dbcbda27afd0/consul-core/src/main/java/com/smoketurner/dropwizard/consul/ConsulBundle.java#L105

This code doesn't use any config pointing to remote Consul, instead assumes Consul is running local. So it builds a Consol instance pointing to local:8500.

**Comment by jplock** [comment]
Users can override `getConsulAgentHost()` and `getConsulAgentPort()` if they need to change the host or the port, but the reason that is there is because we have to do the configuration substitutions before the users can configure consul in the `run()` method.

**Comment by jadams74** [comment]
I think I see how I can get around this, I'll override them via main method args in my consuming app.

**Comment by jadams74** [comment]
First stab here: https://github.com/smoketurner/dropwizard-consul/pull/43

**Comment by jadams74** [comment]
@jplock I have to add support for SSLContext, our corporate consul is https. You want me to include that with the pr here or open a different issue?

**Comment by jplock** [comment]
Fixed in #43

**Comment by jplock** [comment]
Released in v1.2.4-2
