### ISSUE TITLE
Support the Meta field for Service registration

### ISSUE THREAD

**Issue by Imaclean74** [smoketurner/dropwizard-consul#45]
Meta is a block of name, value pairs for tagging rich meta information against a given service instance.

https://www.consul.io/api/agent/service.html

**Comment by jplock** [comment]
Feel free to support a PR

**Comment by Imaclean74** [comment]
absolutely. We have it working locally. Expect the PR fairly shortly.

**Comment by koalalam** [comment]
Here you go - https://github.com/smoketurner/dropwizard-consul/pull/47

**Comment by jplock** [comment]
Released in `v1.3.5-2`
