### ISSUE TITLE
Missing compile time lib dependency (org.jetbrains.annotations.Nullable) ?

### ISSUE THREAD

**Issue by koalalam** [smoketurner/dropwizard-consul#48]
Does the captioned lib come with JDK10? If not, should this lib dep be added explicitly?

https://github.com/smoketurner/dropwizard-consul/commit/bbf8e578b08c6b782dbb8b53ab74b339aef00b02#diff-23dacc491c73bf7aff1e0613a342dddb

**Comment by jplock** [comment]
I added it as an optional dependency in the parent pom but if it’s not being resolved I may have to declare it explicitly

**Comment by koalalam** [comment]
The Java Modular system is new to me.  In case this lib isn't provided by JDK, may I know why marking this lib optional is sufficient?

**Comment by koalalam** [comment]
Hello @jplock , any update on this? If the dependency has to be explicitly declared, any idea when will this be fixed?

**Comment by jplock** [comment]
@koalalam is it causing an issue in your application?  Whenever I deploy my Dropwizard applications, I'm using the Maven Shade plugin and it seems to bring the dependency in properly.

**Comment by jplock** [comment]
I switched over to the spotbugs annotations in https://github.com/smoketurner/dropwizard-consul/commit/74cb6d9175720da25b2dc203e50b2ab4b2b97811 and will be released in v1.3.5-3

**Comment by koalalam** [comment]
Just curious - why do we not use JSR-305? in Java 9+, think we just need to add this module to the build
