### ISSUE TITLE
Make 'deregisterCriticalServiceAfter' configurable

### ISSUE THREAD

**Issue by koalalam** [smoketurner/dropwizard-consul#49]
Currently this is set to 1min

https://www.consul.io/api/agent/check.html#deregistercriticalserviceafter

**Comment by koalalam** [comment]
@jplock , does this make sense? Happy to submit a PR for it

**Comment by jplock** [comment]
@koalalam yes it makes sense.  If you submit a PR, I'll be happy to review it.  Thanks.

**Comment by jplock** [comment]
Fixed in 
https://github.com/smoketurner/dropwizard-consul/commit/74cb6d9175720da25b2dc203e50b2ab4b2b97811 and will be released in v1.3.5-3 shortly.
