### ISSUE TITLE
ConsulServiceCheckTask should not run until after ConsulAdvertiser.register() successfully completes

### ISSUE THREAD

**Issue by mskeefe** [smoketurner/dropwizard-consul#5]
At startup, many messages like "com.orbitz.consul.NotRegisteredException: null" including a stack trace may be logged in the time between the startup of the ConsulServiceCheckTask and the actual registration of the service.  It would be better if ConsulServiceCheckTask did not run until after registration with Consul completes successfully.  At the very least it would be good if the logging was suppressed during this time.

**Comment by jplock** [comment]
That may get tricky with how Dropwizard starts up things, but I'd welcome a pull request addressing it (or at least suppressing the warning message).
