### ISSUE TITLE
Make 'serviceId' configurable

### ISSUE THREAD

**Issue by koalalam** [smoketurner/dropwizard-consul#50]
The default behavior of generating one shall be kept.

https://www.consul.io/api/agent/check.html#serviceid

**Comment by koalalam** [comment]
@jplock , does this make sense? Happy to submit a PR for it

**Comment by jplock** [comment]
@koalalam you can already configure this via the yml file.

**Comment by koalalam** [comment]
I don't seem to see it supported atm - https://github.com/smoketurner/dropwizard-consul/blob/master/consul-core/src/main/java/com/smoketurner/dropwizard/consul/ConsulFactory.java

There is no such field called "serviceID". Instead, service id is provided by the bundle which is an auto-generated GUID:

https://github.com/smoketurner/dropwizard-consul/blob/master/consul-core/src/main/java/com/smoketurner/dropwizard/consul/ConsulBundle.java

@jplock , can you double check? Thank you!

**Comment by jplock** [comment]
You can override it when you initialize the bundle.  For example:

```java
@Override
public void initialize(Bootstrap<HelloWorldConfiguration> bootstrap) {
  bootstrap.addBundle(new ConsulBundle<HelloWorldConfiguration>(getName()) {
    @Override
    public ConsulFactory getConsulFactory(HelloWorldConfiguration configuration) {
      return configuration.getConsulFactory();
    }

    @Override
    public String getConsulServiceId() {
      return 'myserviceid';
    } 
  });
}
```

I think that should work.

**Comment by koalalam** [comment]
But this is no longer coming from YML file. Can we make this configurable from YML file like other properties?

**Comment by jplock** [comment]
I think that would work, trying to remember why I didn't do that I the first place.

**Comment by koalalam** [comment]
We can possibly keep the current implementation as default behavior when Service ID isn't defined in YML file.

Thanks and please let know your finding and I can raise a PR for this enhancement

**Comment by koalalam** [comment]
@jplock , any update on this (why can't the service id come from YML file) please?

**Comment by koalalam** [comment]
@jplock , any update on this please?

**Comment by koalalam** [comment]
@jplock, do you think we can add serviceId to Factory. The serviceId defined in Bundle can be used as default for backward compatibility. Please let me know your thoughts and I am happy to submit a PR for it. Many thanks!

**Comment by jplock** [comment]
@koalalam yes I think we can add serviceId into the Factory.  I'd be happy to review a PR for that.  Thanks.

**Comment by koalalam** [comment]
@jplock , thanks, will work on it. Can you help re-open this issue?  I couldn't find a way of doing it.
