### ISSUE TITLE
Allow Dropwizard app to start when connection to Consul agent fails at startup

### ISSUE THREAD

**Issue by koalalam** [smoketurner/dropwizard-consul#51]
This option shall be made configurable while the default behavior shall be kept (ie the app will terminate when not able to connect to Consul agent). Nice-to-have: auto-retry

**Comment by koalalam** [comment]
@jplock , does this make sense? Happy to submit a PR for it

**Comment by jplock** [comment]
If you want Dropwizard to continue starting up even when Consul isn't available, you can flip the enabled flag at https://github.com/smoketurner/dropwizard-consul/blob/master/consul-core/src/main/java/com/smoketurner/dropwizard/consul/ConsulFactory.java#L41

If you can add auto-retry capabilities without introducing any more dependencies, I'd be happy to review a PR.  Thanks.

**Comment by koalalam** [comment]
Here you go: https://github.com/smoketurner/dropwizard-consul/pull/53

But I think this another issue has to be addressed as well: https://github.com/smoketurner/dropwizard-consul/issues/52
