### ISSUE TITLE
Able to disable ping before service registration

### ISSUE THREAD

**Issue by koalalam** [smoketurner/dropwizard-consul#52]
https://github.com/rickfast/consul-client/blob/1.2.5/src/main/java/com/orbitz/consul/Consul.java#L616

Application would fail to start if target Consul is not running

**Comment by koalalam** [comment]
@jplock , any thoughts?

'ping' is set to true by default so even we add the mechanism to retry when service registration fails, it would not work as the application already shutdown before service registration happens.

I am happy to submit a PR for it.

**Comment by jplock** [comment]
@koalalam if we can make it a configuration option defaulting to the existing behavior, I'd be fine with that.

**Comment by koalalam** [comment]
@jplock , here you go: https://github.com/smoketurner/dropwizard-consul/pull/55
