### ISSUE TITLE
How to provide prefix /template

### ISSUE THREAD

**Issue by mayurbonde** [smoketurner/dropwizard-consul#57]
I have consul configured and it has prefix like 
private-service/master
--application.yml 

http://consul/ui/#/pod/kv/private-service/master/application.yml/edit

I am able to connect the consul but how can i configure the prefix and file name.

i have tried consul.template : "${private-service/master/application.yml}"

Getting error like
 * Unrecognized field at: consul.template
    Did you mean?:
      - tags
      - enabled
      - seviceName
      - endpoint
      - serviceName
        [4 more]

Dropwizard version : 1.1.6
library version : 1.1.1-1

**Comment by jplock** [comment]
I'm not exactly sure, but I feel like this is out of scope for this library.
