### ISSUE TITLE
ConsulAdvertiser.SERVICE_ID should be configurable

### ISSUE THREAD

**Issue by mskeefe** [smoketurner/dropwizard-consul#6]
The random nature of ConsulAdvertiser.SERVICE_ID results in Consul being cluttered with references to services ids that will never be seen again.  This can happen when the JVM terminates unexpectedly without being able to deregister the service successfully.  By allowing a fixed, user-specified service id (e.g. service-name+host:port), recovery will not result in orphaned ids inside of Consul.

**Comment by jplock** [comment]
I agree it should be configurable, but I was worried if you set it to a fixed value, Consul won't let you re-register the service with the same value.
