### ISSUE TITLE
Dropwizard application always send request to localhost:8500 consul

### ISSUE THREAD

**Issue by kdureidy** [smoketurner/dropwizard-consul#95]
I have dropwizard application that is connected Consul on remote server, I run my application from Docker image

I use dropwizard-consul version: 1.3.12-3

Error:

WARN  [2019-10-29 10:26:58,906] com.smoketurner.dropwizard.consul.ConsulBundle: Unable to query Consul running on localhost:8500, disabling configuration substitution
--
  | ! java.net.ConnectException: Connection refused
  | ! at java.net.PlainSocketImpl.socketConnect(Native Method)
  | ! at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  | ! at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  | ! at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  | ! at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  | ! at java.net.Socket.connect(Socket.java:589)
  | ! at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
  | ! at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:246)
  | ! ... 29 common frames omitted
  | ! Causing: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8500
  | ! at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:248)
  | ! at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:166)
  | ! at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
  | ! at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
  | ! at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
  | ! at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
  | ! at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  | ! at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  | ! at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  | ! at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  | ! at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  | ! at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  | ! at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  | ! at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
  | ! at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  | ! at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  | ! at com.orbitz.consul.cache.TimeoutInterceptor.intercept(TimeoutInterceptor.java:53)
  | ! at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  | ! at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  | ! at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
  | ! at okhttp3.RealCall.execute(RealCall.java:92)
  | ! at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
  | ! at com.orbitz.consul.AgentClient.ping(AgentClient.java:62)
  | ! ... 7 common frames omitted
  | ! Causing: com.orbitz.consul.ConsulException: Error connecting to Consul
  | ! at com.orbitz.consul.AgentClient.ping(AgentClient.java:69)
  | ! at com.orbitz.consul.Consul$Builder.build(Consul.java:708)
  | ! at com.smoketurner.dropwizard.consul.ConsulBundle.initialize(ConsulBundle.java:123)
  | ! at io.dropwizard.setup.Bootstrap.addBundle(Bootstrap.java:148)
  | ! at com.dhc.api.dropwizard.ConnectApiApplication.initialize(ConnectApiApplication.java:180)
  | ! at io.dropwizard.Application.run(Application.java:88)
  | ! at com.dhc.api.dropwizard.ConnectApiApplication.run(ConnectApiApplication.java:130)
  | ! at com.dhc.api.dropwizard.ConnectApiApplication.main(ConnectApiApplication.java:96)

**Comment by jplock** [comment]
What does your configuration file look like?

**Comment by kdureidy** [comment]
```
consul:
  # Optional properties
  # endpoint for consul (defaults to localhost:8500)
  endpoint: ${CONSUL_HOST:-localhost}:${CONSUL_PORT:-8500}
  # check interval frequency
  checkInterval: 120 second
  serviceName: sampleApi
  serviceAddress: ${CONSUL_SERVICE_ADDRESS:-localhost}
  deregisterInterval : 5 hour
```

I read the values from environment variables, such as CONSUL_HOST
In the initialization of the project, the first time it tries to connect to localhost, and throws an exception that consul at localhost:8500 does not exist, then it connects to the correct consul that it reads from environment variables.

**Comment by jplock** [comment]
You also need to override https://github.com/smoketurner/dropwizard-consul/blob/master/consul-core/src/main/java/com/smoketurner/dropwizard/consul/ConsulBundle.java#L185 if you want to use the environment variables

**Comment by kdureidy** [comment]
I see now, thanks a lot. should I close this issue? or you are going to handle it in next releases since this is how configuration works with DropWizard?

**Comment by jplock** [comment]
This isn't something that can be fixed because the location of Consul is needed prior to the environment variables being resolved.

**Comment by kdureidy** [comment]
FYI: To fix it, I override two classes, `ConsulBundle`, and `ConsulSubstitutor`
The changed that fixed the issue is that I made `ConsulSubstitutor` extends `EnvironmentVariableSubstitutor`
and enabled substitution in variables parameter `substitutionInVariables=true`
with this change, Consul now initialized after reading the config from the Environment variables

**Comment by jplock** [comment]
@kdureidy if you feel like submitting a pull request with your changes, I’d be happy to review it if we can improve this experience for others. Thanks.

**Comment by kdureidy** [comment]
I have made the fix, I forked the project and submitted a pull request, please check
